# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moodify' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for moodify
  pod 'Firebase/Core'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'FirebaseDatabase'
  pod 'Alamofire', '~> 4.7'

  target 'moodifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'moodifyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
